<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/kidmeeno/image/upload/v1554489632/MyProfile.jpg" alt="Charles Dim">
                        <h6>Bosah Arthur</h6>
                        <p>Front-End Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/kidmeeno_" target="_blank"<i class="fab fa-twitter fa-2x">https://twitter.com/kidmeeno_</i></a></li>
                           <li><a href="https://github.com/kidmeeno" target="_blank"<i class="fab fa-github fa-2x">https://github.com/kidmeeno</i></a></li>
                           <li><a href="https://medium.com/@murphyikechukwu" target="_blank"<i class="fab fa-medium fa-2x">https://medium.com/@murphyikechukwu</i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p> Hello my name is Bosah Arthur. I am a front end developer, 
                        i write javascript and javascript framework using
                        Reactjs and React Native for mobile apps,
                         i am really good at CSS and excellent 
                         knowledge on HTML</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Reactjs | Bootstrap | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
